import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
vm.runInThisContext(fs.readFileSync('renderer/hub-core-v156.js','utf8'));const C=globalThis.GRPGHubCoreV156;
const planet={id:'hub',hub:{maps:[{id:'m',width:1200,height:720,objects:[{id:'alice',npcId:'a',dialogIds:['intro','talk']},{id:'bob',npcId:'b',dialogIds:['intro','follow']}]}],dialogs:[
 {id:'intro',setFlag:'met',startNodeId:'start',nodes:[{id:'start',choices:[]}]},
 {id:'follow',conditions:[{type:'dialog',id:'intro',npcId:'a'}],startNodeId:'start',nodes:[{id:'start',choices:[]}]},
 {id:'talk',startNodeId:'start',nodes:[{id:'start',choices:[{id:'info',nextNodeId:'info',target:'node'},{id:'bye',target:'end'},{id:'secret',target:'end',conditions:[{type:'item',id:'key',location:'equipped'}]}]},{id:'info',text:'Information',choices:[{id:'back',target:'start'}]}]}
]}};
const h=C.hubOf(planet),p={id:'p',currentPlanetId:'hub',inventory:[],equipmentSlots:{}},s=C.stateFor(p,planet,h),alice=h.maps[0].objects[0],bob=h.maps[0].objects[1];
assert.equal(C.dialogsFor(h,bob,p,s).length,1);C.advance(h,'bob','intro','start',null,p,s);assert.equal(C.dialogsFor(h,bob,p,s).length,1,'completion with the wrong NPC does not unlock');C.advance(h,'alice','intro','start',null,p,s);assert.equal(C.dialogsFor(h,bob,p,s).length,2,'completion with Alice unlocks Bob');assert.equal(s.flags.met,true,'dialogue completion applies its flags');assert.ok(C.completedDialog(p,s,{id:'intro',objectId:'alice'}));assert.equal(C.completedDialog(p,s,{id:'intro',npcId:'missing'}),false);
C.storeState(p,s);const reloaded=C.stateFor(JSON.parse(JSON.stringify(p)),planet,h);assert.ok(C.completedDialog(p,reloaded,{id:'intro',npcId:'a'}));
const start=h.dialogs[2].nodes[0],back=h.dialogs[2].nodes[1].choices[0];assert.equal(C.destination(h.dialogs[2],back),'start');C.advance(h,'alice','talk','start','info',p,s);C.advance(h,'alice','talk','info','back',p,s);assert.equal(s.dialogCursors[C.key('talk','m','alice')],'start');assert.equal(s.completedDialogs.talk,undefined,'returning to start is not completion');C.advance(h,'alice','talk','start','info',p,s);C.advance(h,'alice','talk','info','back',p,s);C.advance(h,'alice','talk','start','bye',p,s);assert.equal(s.completedDialogs.talk,true);
assert.ok(C.choiceReason(h.dialogs[2],start,start.choices[2],p,s,alice));p.implantSlots=['key'];assert.equal(C.choiceReason(h.dialogs[2],start,start.choices[2],p,s,alice),'');
assert.equal(C.reason({conditionMode:'any',conditions:[{type:'flag',id:'missing'},{type:'item',id:'key',location:'equipped'}]},p,s),'');assert.ok(C.reason({conditionMode:'all',conditions:[{type:'flag',id:'missing'},{type:'item',id:'key'}]},p,s));assert.equal(C.reason({conditions:[{type:'dialog',id:'unknown',value:false}]},p,s),'');
const other={id:'other',inventory:[]},otherState=C.stateFor(other,planet,h);assert.equal(C.completedDialog(other,otherState,{id:'intro',npcId:'a'}),false,'completion is per character');
assert.equal(C.completedDialog(p,C.stateFor(p,{id:'away',hub:{}},C.hubOf({hub:{}})),{id:'intro',npcId:'a'}),true,'completion is retained in saved hub progress');
const before=C.clone(s),unset={id:'unset',target:'unset'};start.choices.push(unset);assert.ok(C.choiceReason(h.dialogs[2],start,unset,p,s,alice));assert.throws(()=>C.advance(h,'alice','talk','start','unset',p,s));assert.deepEqual(s,before,'invalid reply has no side effects');assert.ok(C.validate(h).some(x=>/destination/.test(x)));start.choices.pop();
const once=h.dialogs[2].nodes[1];once.once=true;const state=C.stateFor({id:'fresh'},planet,h);C.advance(h,'alice','talk','start','info',other,state);C.advance(h,'alice','talk','info','back',other,state);assert.ok(C.choiceReason(h.dialogs[2],start,start.choices[0],other,state,alice));
once.once=false;start.choices[0].once=true;const replyState=C.stateFor({id:'reply-player'},planet,h);C.advance(h,'alice','talk','start','info',other,replyState);C.advance(h,'alice','talk','info','back',other,replyState);assert.ok(C.choiceReason(h.dialogs[2],start,start.choices[0],other,replyState,alice),'one-time reply cannot be repeated after returning to the start');start.choices[0].once=false;
const diagnostics=C.inspectDialog({id:'bad',startNodeId:'a',nodes:[{id:'a',terminal:false,choices:[{id:'x',target:'unset'}]},{id:'isolated',terminal:true,choices:[]}]});assert.ok(diagnostics.some(x=>x.level==='error'));assert.ok(diagnostics.some(x=>x.level==='warning'&&x.nodeId==='isolated'));
assert.equal(C.completedDialog(p,{planetId:'away',completedDialogs:{}},{id:'intro'}),false,'legacy prerequisites remain scoped to the current Hub');
assert.equal(C.validate(C.hubOf(planet)).length,0,'legacy no-reply endings remain compatible');
for(const file of ['hub-core-v156.js','hub-runtime-v156.js','dialog-view-v161.js','dialog-v161.css'])assert.equal(fs.readFileSync('renderer/'+file,'utf8'),fs.readFileSync('deploy/site/app/'+file,'utf8'));
console.log('RPG dialogue rules: branches, repeated return-to-start, explicit ends, per-NPC completion/reload, item and ANY/ALL conditions, once-only replies, invalid graph and compatibility passed');
