// PLAYWRIGHT_CORE_PATH=/path/to/playwright-core CHROMIUM_PATH=/path/to/chromium node tests/dialogues-v161.browser.mjs
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/tmp/grpgi-dialog-chromium/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
async function fixture(page,folder){
 await page.route('https://dialog.test/**',async route=>{const pathname=new URL(route.request().url()).pathname;if(pathname==='/'){return route.fulfill({body:'<html><head><meta charset="utf-8"></head><body style="margin:0;background:#10151d;color:#eee"><main id="hub"></main></body></html>',contentType:'text/html'});}if(pathname==='/portrait.png')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWhoAAAAASUVORK5CYII=','base64')});return route.fulfill({body:await fs.readFile(pathname.slice(1)),contentType:pathname.endsWith('.css')?'text/css':'text/javascript; charset=utf-8'});});
 await page.goto('https://dialog.test/');for(const file of ['hub-v153.css','dialog-v161.css'])await page.addStyleTag({url:'https://dialog.test/'+folder+'/'+file});
 for(const file of ['hub-core-v156.js','hub-spatial-v157.js','dialog-view-v161.js','hub-runtime-v156.js'])await page.addScriptTag({url:'https://dialog.test/'+folder+'/'+file});
 await page.evaluate(()=>{
  window.planet={id:'h',name:'Hub',locationType:'hub',hub:{maps:[{id:'m',name:'Hall',width:900,height:720,fogEnabled:false,objects:[{id:'a',name:'Alice',npcId:'alice',type:'npc',dialogIds:['intro','talk'],x:160,y:100,width:48,height:48},{id:'b',name:'Bob',npcId:'bob',type:'npc',dialogIds:['follow'],x:240,y:100,width:48,height:48}]}],dialogs:[{id:'intro',name:'Meet Alice',startNodeId:'start',nodes:[{id:'start',text:'Welcome.',choices:[]}]},{id:'follow',name:'Bob follow-up',startNodeId:'start',conditions:[{type:'dialog',id:'intro',npcId:'alice'}],nodes:[{id:'start',text:'Alice told me about you.',choices:[]}]},{id:'talk',name:'Ask Alice',startNodeId:'start',nodes:[{id:'start',name:'Greeting',text:'How can I help?',choices:[{id:'ask',text:'Tell me about the hub',nextNodeId:'info'},{id:'secret',text:'Secret route',unavailable:'hide',conditions:[{type:'flag',id:'secret'}],target:'end'},{id:'key',text:'Use key',blockedText:'Equip the key first.',conditions:[{type:'item',id:'key',location:'equipped'}],target:'end'},{id:'bye',text:'Goodbye',target:'end'}]},{id:'info',name:'Information',text:'The hub has two halls.',choices:[{id:'back',text:'Ask something else',target:'start'}]}]}],flags:[{id:'secret',name:'Knows secret'}]}};
  window.player={id:'p',currentPlanetId:'h',role:'player',displayName:'Player',inventory:[],equipmentSlots:{}};window.commits=[];window.fail=false;window.delay=0;window.active=true;window.npcs=[{id:'alice',name:'Alice',image:'https://dialog.test/portrait.png'},{id:'bob',name:'Bob'}];
  window.runtime=GRPGHubRuntimeV156.create({root:()=>document.getElementById('hub'),currentPlayer:()=>player,currentPlanet:()=>planet,isActive:()=>active,npc:id=>npcs.find(n=>n.id===id),activate(){},openStocks(){},notify(){},item(){},article(){},async commit(mutator,notice){const next=structuredClone(player);mutator(next);commits.push({notice,next});await new Promise(r=>setTimeout(r,delay));if(fail)throw Error('Save failed');player=next;}});runtime.show();
 });
}
try{
 for(const folder of ['renderer','deploy/site/app']){
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,folder);
  await page.evaluate(()=>runtime.select('b'));assert.equal(await page.locator('[data-dialog="follow"]').count(),0);
  await page.evaluate(()=>runtime.openDialog('a','talk'));const box=await page.locator('.hub-conversation-v161').boundingBox();assert.equal(box.width,1440);assert.equal(box.height,1000);assert.equal(await page.locator('[data-choice]').count(),3);assert.equal(await page.locator('[data-choice="key"]').isDisabled(),true);assert.equal(await page.locator('[data-speaker-portrait] img').getAttribute('src'),'https://dialog.test/portrait.png');
  await page.locator('[data-choice="ask"]').click();await page.waitForSelector('[data-choice="back"]');await page.locator('[data-choice="back"]').click();await page.waitForSelector('[data-choice="ask"]');await page.locator('[data-choice="ask"]').click();await page.waitForSelector('[data-choice="back"]');await page.locator('[data-leave]').click();assert.equal(await page.evaluate(()=>player.hubState.completedDialogs.talk),undefined);assert.equal(await page.evaluate(()=>commits.every(c=>c.notice===null)),true);
  await page.evaluate(()=>runtime.openDialog('a','talk'));await page.waitForSelector('[data-choice="back"]');await page.keyboard.press('Escape');assert.equal(await page.locator('.hub-conversation-v161').count(),0);assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
  await page.evaluate(()=>runtime.openDialog('a','intro'));await page.locator('[data-finish]').click();await page.waitForSelector('.hub-conversation-v161',{state:'detached'});await page.evaluate(()=>runtime.select('b'));assert.equal(await page.locator('[data-dialog="follow"]').count(),1);
  await page.locator('[data-dialog="follow"]').click();await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('[data-leave]').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);await page.screenshot({path:'/tmp/dialog-mobile-v161-'+folder.replaceAll('/','-')+'.png'});await page.locator('[data-leave]').click();assert.equal(await page.evaluate(()=>player.hubState.completedDialogs.follow),undefined);
  await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{runtime.openDialog('a','talk');fail=true;});await page.locator('[data-choice="back"]').click();await page.waitForFunction(()=>document.querySelector('.hub-conversation-v161 [data-status]').textContent==='Save failed');assert.equal(await page.locator('[data-choice="back"]').isEnabled(),true);assert.equal(await page.evaluate(()=>player.hubState.dialogCursors[GRPGHubCoreV156.key('talk','m','a')]),'info');await page.evaluate(()=>fail=false);await page.locator('[data-choice="back"]').click();await page.waitForSelector('[data-choice="bye"]');await page.locator('[data-choice="bye"]').click();await page.waitForSelector('.hub-conversation-v161',{state:'detached'});assert.equal(await page.evaluate(()=>player.hubState.completedDialogs.talk),true);
  await page.evaluate(()=>{player.hubState.dialogCursors={};delay=150;runtime.openDialog('a','talk');});await page.locator('[data-choice="ask"]').click();await page.locator('[data-leave]').click();await page.waitForTimeout(200);assert.equal(await page.locator('.hub-conversation-v161').count(),0,'pending choice must not reopen the screen after leaving');
  assert.deepEqual(errors,[]);await page.close();console.log(folder+': full-screen branches, loops, Leave/Escape/resume, cross-NPC unlock, portrait, disabled/hidden replies, save failure/retry and mobile passed');
 }
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,'renderer');
 for(const file of ['hub-authoring-v156.js','dialog-editor-v161.js'])await page.addScriptTag({url:'https://dialog.test/renderer/'+file});
 await page.evaluate(()=>{window.draft=GRPGHubCoreV156.hubOf(planet);window.originalPlayer=JSON.stringify(player);window.savedCalls=0;window.saveOk=false;GRPGHubAuthoringV156.openDialogs({hub:draft,items:[{id:'key',name:'Key'}],npcs,planetId:'h',testPlayer:player,onSave:async()=>{savedCalls++;return {ok:saveOk,message:'Save failed'};}});});
 await page.locator('[data-select-dialog="talk"]').click();assert.equal(await page.locator('[data-column] textarea').count(),0,'graph cards must remain compact');await page.locator('[data-column="start"] [data-select-node]').click();await page.locator('[data-inspector] textarea').fill('Updated greeting');assert.equal(await page.evaluate(()=>draft.dialogs.find(d=>d.id==='talk').nodes[0].text),'Updated greeting');
 await page.locator('[data-column="start"] [data-add-choice]').click();await page.locator('[data-inspector] [data-field="text"]').fill('Another topic');await page.locator('[data-check]').click();assert.match(await page.locator('[data-graph-status]').innerText(),/destination/);await page.locator('[data-save-dialogs]').click();assert.equal(await page.evaluate(()=>savedCalls),0,'invalid graph cannot be saved');
 const output=page.locator('[data-column="start"] [data-node-output]').last(),r=await output.boundingBox(),viewport=await page.locator('[data-graph-viewport]').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(viewport.x+viewport.width*.8,viewport.y+viewport.height*.7,{steps:12});await page.mouse.up();assert.equal(await page.locator('[data-column]').count(),3);const created=await page.evaluate(()=>draft.dialogs.find(d=>d.id==='talk').nodes.at(-1).id);await page.locator('[data-inspector] [data-field="text"]').fill('Topic details');await page.locator('[data-inspector] [data-field="terminal"]').check();
 await page.locator('[data-column="start"] [data-select-reply]').last().click();await page.locator('[data-condition-add]').click();await page.locator('[data-condition-field="type"]').selectOption('dialog');await page.locator('[data-condition-field="id"]').selectOption('intro');await page.locator('[data-condition-field="npcId"]').selectOption('alice');await page.locator('[data-field="conditionMode"]').selectOption('any');assert.equal(await page.evaluate(()=>draft.dialogs.find(d=>d.id==='talk').nodes[0].choices.at(-1).conditions[0].npcId),'alice');
 await page.locator('[data-preview]').click();await page.locator('[data-run-test]').click();assert.equal(await page.locator('[data-choice]').filter({hasText:'Another topic'}).isDisabled(),true);await page.locator('[data-leave]').click();await page.locator('[data-test-dialog="intro"]').check();await page.locator('[data-test-dialog-npc="intro"]').selectOption('alice');await page.locator('[data-test-equipped="key"]').check();await page.locator('[data-run-test]').click();await page.locator('[data-choice]').filter({hasText:'Another topic'}).click();await page.waitForSelector('[data-finish]');await page.locator('[data-finish]').click();assert.equal(await page.evaluate(()=>JSON.stringify(player)===originalPlayer),true);await page.locator('[data-close-test]').click();
 await page.locator('[data-save-dialogs]').click();await page.waitForFunction(()=>savedCalls===1&&!document.querySelector('.dlg-editor-v161').inert);assert.equal(await page.locator('.dlg-editor-v161').count(),1);assert.match(await page.locator('[data-graph-status]').innerText(),/Save failed/);
 await page.locator('[data-column="'+created+'"] [data-select-node]').click();await page.locator('[data-inspector] [data-field="text"]').fill('Changed text');await page.locator('.dlg-editor-v161 [data-undo]').click();assert.equal(await page.evaluate(id=>draft.dialogs.find(d=>d.id==='talk').nodes.find(n=>n.id===id).text,created),'Topic details');await page.locator('.dlg-editor-v161 [data-redo]').click();assert.equal(await page.evaluate(id=>draft.dialogs.find(d=>d.id==='talk').nodes.find(n=>n.id===id).text,created),'Changed text');
 await page.locator('[data-fit]').click();await page.screenshot({path:'/tmp/dialog-editor-v161.png'});await page.setViewportSize({width:760,height:900});await page.locator('[data-pane="properties"]').click();assert.equal(await page.locator('[data-inspector] textarea').isVisible(),true);await page.locator('[data-pane="graph"]').click();assert.equal(await page.locator('[data-graph-viewport]').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=760),true);await page.setViewportSize({width:1440,height:1000});
 await page.evaluate(()=>saveOk=true);await page.locator('[data-save-dialogs]').click();await page.waitForSelector('.dlg-editor-v161',{state:'detached'});assert.equal(await page.evaluate(()=>savedCalls),2);assert.deepEqual(errors,[]);await page.close();console.log('Editor: compact branching cards, drag-create links, explicit destinations, NPC conditions, isolated test character, save validation/failure/retry, undo/redo and responsive inspector passed');
}finally{await browser.close();}
