import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire}from'node:module';
const require=createRequire(import.meta.url),pw=process.env.PLAYWRIGHT_CORE_PATH||'/tmp/grpgi-news-test/node_modules/playwright-core';const{chromium}=require(pw);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/grpgi-news-chromium/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
try{
const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://example.test/**',route=>route.fulfill({contentType:'text/html',body:'<html></html>'}));await page.route('https://images.test/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWhoAAAAASUVORK5CYII=','base64')}));await page.goto('https://example.test/');
await page.setContent('<html><head></head><body style="background:#101923;color:#ddd"><main id="screen-news"></main></body></html>');
await page.addStyleTag({content:await fs.readFile('renderer/news-v159.css','utf8')});for(const f of ['news-core-v159.js','news-ui-v159.js'])await page.addScriptTag({content:await fs.readFile('renderer/'+f,'utf8')});
await page.evaluate(()=>{window.owner={id:'hero',displayName:'Hero',role:'player'};window.players=[owner,{id:'other',displayName:'Other',newsPosts:{other:{id:'other',campaignId:'c',body:'Other post',publishedAt:'3159-01-01'}}}];window.world=[{id:'old',title:'Legacy news',body:'<b>Legacy rich content</b>',publishedAt:'3159-01-01'},{id:'org',authorType:'organization',authorName:'Trade Union',title:'Organization update'},{id:'npc',authorType:'npc',authorNpcId:'npc',title:'NPC update'}];window.fail=true;window.uploads=0;window.writes=[];window.failUpload=false;
window.feed=GRPGNewsUIV159.create({root:()=>document.getElementById('screen-news'),current:()=>owner,campaign:()=> 'c',world:()=>world,players:()=>players,visible:()=>true,npc:()=>({name:'Captain'}),rich:s=>s,date:()=> '3160-01-01',notify:()=>{},upload:async()=>{uploads++;if(failUpload)throw Error('Upload failed');return 'https://images.test/one.png';},commit:async(fn)=>{const next=structuredClone(owner);fn(next);writes.push(next);if(fail)throw Error('Save failed');Object.assign(owner,next);feed.show();}});feed.show();});
assert.match(await page.locator('[data-feed]').innerText(),/Trade Union/);assert.match(await page.locator('[data-feed]').innerText(),/Captain/);assert.equal(await page.locator('[data-feed] b').filter({hasText:'Legacy rich content'}).count(),1);assert.equal(await page.locator('[data-delete]').count(),0);
await page.locator('textarea').fill('<script>alert(1)</script> Player report');await page.locator('input[type=file]').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from('fake-image')});await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent==='Save failed');assert.match(await page.locator('textarea').inputValue(),/Player report/);assert.equal(await page.evaluate(()=>uploads),1);
await page.evaluate(()=>feed.show());assert.match(await page.locator('textarea').inputValue(),/Player report/);await page.evaluate(()=>fail=false);await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent==='Опубликовано');assert.equal(await page.evaluate(()=>uploads),1);assert.equal(await page.evaluate(()=>writes[0].newsPosts[Object.keys(writes[0].newsPosts)[0]].id===writes[1].newsPosts[Object.keys(writes[1].newsPosts)[0]].id),true);assert.equal(await page.locator('textarea').inputValue(),'');assert.equal(await page.evaluate(()=>Object.values(owner.newsPosts)[0].publishedAt.slice(0,4)),'3616');assert.equal(await page.evaluate(()=>{const p=Object.values(owner.newsPosts)[0];return p.publishedAt.slice(4)===p.createdAt.slice(4);}),true);assert.equal(await page.locator('[data-feed] script').count(),0);assert.equal(await page.locator('[data-delete]').count(),1);
page.on('dialog',d=>d.accept());await page.locator('[data-delete]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-delete]').length===0);
await page.locator('textarea').fill('Retain on upload error');await page.locator('input[type=file]').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from('image')});await page.evaluate(()=>failUpload=true);await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent==='Upload failed');assert.equal(await page.locator('textarea').inputValue(),'Retain on upload error');await page.evaluate(()=>failUpload=false);await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent==='Опубликовано');
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);await page.screenshot({path:'/tmp/grpgi-galagram-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
console.log('GalaGram browser: author bylines, composer, images, escaped text, retry ID, draft preservation, deletion, refresh and mobile layout passed');
}finally{await browser.close();}
