// PLAYWRIGHT_CORE_PATH=/path/to/playwright-core CHROMIUM_PATH=/path/to/chromium node tests/hub-navigation-v160.browser.mjs
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'/tmp/grpgi-news-test/node_modules/playwright-core');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/grpgi-news-chromium/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
try{for(const folder of ['renderer','deploy/site/app']){
 const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://hub.test/**',r=>r.fulfill({body:'<html><body style="background:#101923;color:#eee"><main id="hub"></main></body></html>',contentType:'text/html'}));await page.goto('https://hub.test/');await page.addStyleTag({content:await fs.readFile(folder+'/hub-v153.css','utf8')});
 for(const file of ['hub-core-v156.js','hub-spatial-v157.js','hub-runtime-v156.js'])await page.addScriptTag({content:await fs.readFile(folder+'/'+file,'utf8')});
 await page.evaluate(()=>{
  const S=GRPGHubSpatialV157;window.map={id:'main',name:'Map',width:900,height:720,hexSize:28,fogEnabled:true,visionRange:0,walls:[{id:'wall',thickness:8,blockMovement:true,blockSight:true,points:[{x:650,y:0},{x:650,y:720}]}],objects:[],spawnPoints:[]};window.start=S.center(map,{q:1,r:4});map.spawnPoints=[{id:'entry',...start}];map.objects=[{id:'sign',kind:'asset',type:'decor',x:start.x-20,y:start.y-20,width:40,height:40,name:'Sign',dialogIds:['read']}];window.planet={id:'hub',name:'Hub',locationType:'hub',hub:{maps:[map],defaultMapId:'main',dialogs:[{id:'read',name:'Read',nodes:[{id:'first',text:'Text',choices:[]}],startNodeId:'first'}]}};
  window.player={id:'p',role:'player',currentPlanetId:'hub',displayName:'Player'};window.calls=[];window.notices=[];window.fail=false;window.active=true;
  window.runtime=GRPGHubRuntimeV156.create({root:()=>document.getElementById('hub'),currentPlayer:()=>player,currentPlanet:()=>planet,isActive:()=>active,activate(){},notify:(m,t)=>notices.push({m,t}),openStocks(){},article:()=>null,
    async commit(mutator,notice){const next=structuredClone(player);mutator(next);const c={notice,start:performance.now(),state:structuredClone(next.hubState)};calls.push(c);await new Promise(r=>setTimeout(r,220));c.end=performance.now();if(fail)throw Error('Save failed');player=next;}
  });runtime.show();
 });
 await page.evaluate(()=>runtime.openDialog('sign','read'));await page.locator('[data-finish]').click();await page.waitForSelector('.hub-modal-v153',{state:'detached'});assert.equal(await page.evaluate(()=>calls[0].notice),null);assert.equal(await page.evaluate(()=>player.hubState.completedDialogs.read),true);
 const goal=await page.evaluate(()=>GRPGHubSpatialV157.center(map,{q:5,r:4})),rect=await page.locator('[data-runtime-map]').boundingBox();await page.mouse.move(rect.x+goal.x,rect.y+goal.y);await page.waitForSelector('[data-route] polyline',{state:'attached'});
 await page.screenshot({path:'/tmp/hub-route-v160-'+folder.replaceAll('/','-')+'.png'});
 const expected=await page.evaluate(goal=>GRPGHubSpatialV157.path(map,GRPGHubCoreV156.stateFor(player,planet,GRPGHubCoreV156.hubOf(planet)),goal.x,goal.y).map(p=>({x:p.x,y:p.y})),goal);
 const circles=await page.locator('[data-route] circle').evaluateAll(nodes=>nodes.map(n=>({x:+n.getAttribute('cx'),y:+n.getAttribute('cy')})));assert.deepEqual(circles,expected);const key=await page.locator('[data-route]').innerHTML();await page.mouse.move(rect.x+goal.x+2,rect.y+goal.y+2);assert.equal(await page.locator('[data-route]').innerHTML(),key);
 const blocked=await page.evaluate(()=>GRPGHubSpatialV157.center(map,{q:13,r:4}));await page.mouse.move(rect.x+blocked.x,rect.y+blocked.y);await page.waitForSelector('.hub-route-blocked-v160');assert.equal(await page.locator('[data-route] polyline').count(),0);
 await page.mouse.move(rect.x+goal.x,rect.y+goal.y);await page.waitForSelector('[data-route] polyline',{state:'attached'});await page.mouse.move(1100,800);await page.waitForFunction(()=>document.querySelector('[data-route]').childElementCount===0);
 await page.evaluate(()=>{calls=[];});await page.mouse.click(rect.x+goal.x,rect.y+goal.y);await page.waitForFunction(()=>calls.length===1);await page.waitForTimeout(70);
 const pending=await page.evaluate(first=>{const n=document.querySelector('.hub-player-v153'),canvas=document.querySelector('[data-fog]');return{saved:!!calls[0].end,x:parseFloat(getComputedStyle(n).left),fog:canvas.getContext('2d').getImageData(Math.round(first.x),Math.round(first.y),1,1).data[3]};},expected[0]);assert.equal(pending.saved,false);assert.ok(pending.x>await page.evaluate(()=>start.x),'animation begins during persistence');assert.ok(pending.fog>0,'fog waits for confirmed step');
 await page.waitForFunction(()=>calls.length===4&&!document.querySelector('.hub-walking-v157'));const timings=await page.evaluate(()=>calls);assert.ok(timings.every(c=>c.notice===null));for(let i=1;i<timings.length;i++)assert.ok(timings[i].start-timings[i-1].end<120,'no extra animation wait after the save');assert.equal(await page.evaluate(()=>player.hubState.x),goal.x);assert.equal(await page.locator('[data-route]').evaluate(n=>n.childElementCount),0);assert.equal(await page.locator('[data-fog]').evaluate((c,p)=>c.getContext('2d').getImageData(Math.round(p.x),Math.round(p.y),1,1).data[3],goal),0);
 const before=await page.evaluate(()=>structuredClone(player.hubState)),next=await page.evaluate(()=>GRPGHubSpatialV157.center(map,{q:6,r:4}));await page.evaluate(()=>fail=true);await page.mouse.click(rect.x+next.x,rect.y+next.y);await page.waitForFunction(()=>notices.length&&!document.querySelector('.hub-walking-v157'));assert.deepEqual(await page.evaluate(()=>player.hubState),before);assert.ok(Math.abs(await page.locator('.hub-player-v153').evaluate(n=>parseFloat(n.style.left))-before.x)<.001);assert.equal(await page.evaluate(()=>notices[0].m),'Save failed');
 assert.deepEqual(errors,[]);await page.close();console.log(folder+': hover/blocked/leave route, quiet dialogue and navigation, concurrent save/animation, fog confirmation, speed and failure rollback passed');
}}finally{await browser.close();}
