// PLAYWRIGHT_CORE_PATH=/path/to/playwright-core CHROMIUM_PATH=/path/to/chromium node tests/merchant-terminal-v163.browser.mjs
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'/tmp/grpgi-merchant-test/node_modules/playwright-core');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/tmp/grpgi-merchant-chromium/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
const web=await fs.readFile('deploy/site/app/app.js','utf8'),desktop=await fs.readFile('renderer/app.js','utf8');
// Execute the real clients' inventory layout/capacity helpers and web bridge; replace only unrelated application services.
const webInventory=web.slice(web.indexOf('  const DEFAULT_INVENTORY_SIZE_V1067'),web.indexOf('  function webSlotLabelV1067'));
const desktopInventory=desktop.slice(desktop.indexOf('  function itemForInventoryV1067'),desktop.indexOf("  window.GRPGInventoryV1067 ="));
const webBridge=web.slice(web.indexOf('  window.GRPGHubBridgeV153 = {'),web.indexOf('  const renderProfileBeforeSheetV142',web.indexOf('  window.GRPGHubBridgeV153 = {')));
try{for(const folder of ['renderer','deploy/site/app']){
 const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://trade.test/**',async route=>{const p=new URL(route.request().url()).pathname;if(p==='/'){return route.fulfill({contentType:'text/html',body:'<html><head><meta charset="utf-8"></head><body style="margin:0;background:#10151d;color:#eee;font-family:Arial"><main id="hub"></main><div id="screen-hub-v153" class="screen"></div><button id="nav-hub-v153">Hub</button></body></html>'});}if(p==='/gun.svg')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="150" height="200"><path fill="#bd9860" d="M20 50h110v40H95v85H70v-85H20z"/></svg>'});if(p==='/armor.svg')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><path fill="#75887d" d="M40 30h100l30 110-80 30-80-30z"/></svg>'});if(p==='/bad.png')return route.abort();return route.fulfill({body:await fs.readFile(p.slice(1)),contentType:p.endsWith('.css')?'text/css':'text/javascript'});});
 await page.goto('https://trade.test/');for(const f of ['hub-v153.css','merchant-v163.css'])await page.addStyleTag({url:`https://trade.test/${folder}/${f}`});
 for(const f of ['market-engine.js','market-categories-v144.js','item-facts-v141.js','hub-core-v156.js','hub-spatial-v157.js','dialog-view-v161.js','merchant-ui-v163.js','hub-runtime-v156.js'])await page.addScriptTag({url:`https://trade.test/${folder}/${f}`});
 await page.evaluate(()=>{
  window.deep=x=>JSON.parse(JSON.stringify(x));window.esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.normalizedItemTypeV1052=i=>i.type;window.normalizeEquipmentItemV2=i=>i;window.intNonNegativeV1067=(v,f=0)=>Number.isFinite(Number(v))?Math.max(0,Math.floor(Number(v))):f;window.normalizePositionV1067=p=>p&&Number.isInteger(p.x)&&Number.isInteger(p.y)?p:null;window.itemSizeV1067=i=>({w:Math.max(1,Number(i.inventoryWidth)||1),h:Math.max(1,Number(i.inventoryHeight)||1)});window.itemMassV1067=i=>Number(i.mass??1);window.normalizePlayerProfileV2=p=>deep(p);
  window.EQUIPMENT={gun:{id:'gun',name:'SCR-22',type:'weapon',image:'https://trade.test/gun.svg',inventoryWidth:2,inventoryHeight:3,mass:3,damage:2,range:25,hitBonus:1,magazineSize:25,rapidFireShots:3,ammoFamily:'6.5',description:'Rapid-fire rifle.',requirements:{strength:2},tags:['Rifle']},armor:{id:'armor',name:'Field armor',type:'armor',image:'https://trade.test/armor.svg',inventoryWidth:2,inventoryHeight:2,mass:2,armorClass:12,damageReduction:1,description:'Protective plates.'},token:{id:'token',name:'Token',type:'gear',image:'https://trade.test/bad.png',inventoryWidth:1,inventoryHeight:1,mass:0},key:{id:'key',name:'Key',type:'gear',inventoryWidth:1,inventoryHeight:1,mass:0}};
  window.player={id:'p',role:'player',currentPlanetId:'h',inventorySize:40,carryWeightMax:100,credits:100,inventory:[{itemId:'armor',qty:2,positions:[]},{itemId:'key',qty:1,positions:[]}],equipmentSlots:{armor:'armor'},implantSlots:[]};
  window.planet={id:'h',locationType:'hub',hub:{defaultMapId:'m',maps:[{id:'m',name:'Hall',width:900,height:720,spawnPoints:[{id:'entry',x:100,y:100}],objects:[{id:'merchant',type:'npc',name:'Equipment trader',x:160,y:100,width:48,height:48,trader:true,merchantMarket:['gun','armor','token'].map(itemId=>({itemId,enabled:true,appearanceChance:100,minPrice:itemId==='gun'?10:5,maxPrice:itemId==='gun'?10:5}))}]}],dialogs:[]}};
  window.campaign={marketDate:'3616-10-07'};window.notices=[];window.fail=false;window.delay=0;window.savedCount=0;window.active=true;
  window.App={ui:{screen:'hub-v153'},config:{campaignId:'main'},data:{items:new Map(Object.values(EQUIPMENT).map(i=>[i.id,i])),campaigns:new Map([['main',campaign]]),planets:new Map([['h',planet]]),npcs:new Map(),articles:new Map()}};window.Data={getItem:id=>EQUIPMENT[id]};
  window.currentPlayer=()=>player;window.currentPlanet=()=>planet;window.notify=(m,t)=>notices.push({m,t});window.renderEntityThumb=i=>`<div class="entity-thumb">${i.image?`<img src="${i.image}" alt="${i.name}">`:`<span>${i.name.slice(0,2)}</span>`}</div>`;window.openArticleById=()=>{};window.marketTabWebV1073='';window.renderCurrentScreen=()=>{};
  window.commitPlayerMutation=async(mutator)=>{const next=deep(player);await mutator(next);await new Promise(r=>setTimeout(r,delay));if(fail)throw Error('Save failed');player=next;savedCount++;};
 });
 if(folder==='renderer'){
  await page.addScriptTag({content:desktopInventory+'\nwindow.GRPGInventoryV1067={canAddItem:canAddInventoryItemV1067,buildLayout:buildInventoryLayoutV1067};'});
  await page.evaluate(()=>{window.runtime=GRPGHubRuntimeV156.create({root:()=>document.getElementById('hub'),currentPlayer,currentPlanet,isActive:()=>active,item:id=>EQUIPMENT[id],itemThumb:renderEntityThumb,inventoryLayout:GRPGInventoryV1067.buildLayout,marketContext:()=>({campaignId:'main',campaign}),canAdd:GRPGInventoryV1067.canAddItem,commit:commitPlayerMutation,notify});runtime.show();runtime.merchant('merchant');});
 }else{
  await page.addScriptTag({content:webInventory});await page.addScriptTag({content:webBridge});await page.addScriptTag({url:'https://trade.test/deploy/site/app/hub-v153.js'});await page.evaluate(()=>GRPGHubV153.show());await page.locator('[data-object="merchant"]').click();await page.locator('[data-trade]').click();
 }
 const market=id=>page.locator(`[data-trade-item="${id}"][data-source="market"]`),buy=page.locator('[data-buy]');
 assert.equal(await page.locator('.hub-trade-v163').getAttribute('role'),'dialog');assert.ok(!(await page.locator('.hub-trade-v163').textContent()).includes('Daily assortment'));
 await page.waitForFunction(()=>document.querySelector('[data-trade-item="gun"] img').complete);assert.equal(await market('gun').locator('img').getAttribute('src'),'https://trade.test/gun.svg');
 const gunRect=await market('gun').boundingBox(),tokenRect=await market('token').boundingBox();assert.ok(gunRect.width>tokenRect.width*1.7);assert.ok(gunRect.height>tokenRect.height*2.5);assert.equal(await market('gun').evaluate(n=>n.style.gridColumn),'span 2');assert.equal(await market('gun').evaluate(n=>n.style.gridRow),'span 3');
 assert.equal(await page.locator('[data-trade-inventory] [data-trade-item="armor"]').count(),1);assert.equal(await page.locator('[data-trade-equipped] [data-trade-item="armor"]').count(),1);assert.ok((await page.locator('[data-trade-capacity]').textContent()).includes('40 cells'));
 const goods=await page.locator('.hub-trade-goods-v163').boundingBox(),inv=await page.locator('.hub-trade-inventory-v163').boundingBox();assert.ok(goods.x<inv.x);assert.ok(goods.x+goods.width<=inv.x);
 await market('gun').click();const details=page.locator('[data-trade-details]');for(const text of ['Rapid-fire rifle.','25','3','strength: 2','Rifle'])assert.ok((await details.textContent()).includes(text));assert.equal(await details.locator('img').count(),1);
 await page.locator('[data-trade-quantity]').fill('2');assert.equal(await page.locator('[data-trade-total]').textContent(),'20');await page.evaluate(()=>fail=true);await buy.click();await page.waitForFunction(()=>document.querySelector('.hub-trade-v163 [data-status]').textContent.length>0);assert.equal(await page.locator('.hub-trade-v163 [data-status]').textContent(),'Save failed');assert.equal(await page.evaluate(()=>player.credits),100);assert.equal(await page.evaluate(()=>player.inventory.some(e=>e.itemId==='gun')),false);
 await page.evaluate(()=>fail=false);await buy.click();await page.waitForFunction(()=>player.credits===80);assert.equal(await page.evaluate(()=>player.inventory.find(e=>e.itemId==='gun').qty),2);assert.equal(await page.locator('[data-trade-inventory] [data-trade-item="gun"]').count(),2);
 await page.locator('[data-trade-equipped] [data-trade-item="armor"]').click();assert.equal(await page.locator('[data-sell]').count(),0);assert.ok((await details.textContent()).includes('Equipped'));
 await page.locator('[data-trade-inventory] [data-trade-item="armor"]').click();assert.equal(await page.locator('[data-sell]').count(),1);await page.evaluate(()=>fail=true);await page.locator('[data-sell]').click();await page.waitForFunction(()=>document.querySelector('.hub-trade-v163').dataset.busy!=='1'&&!document.querySelector('[data-close]').disabled);assert.equal(await page.evaluate(()=>player.inventory.find(e=>e.itemId==='armor').qty),2);
 await page.evaluate(()=>fail=false);await page.locator('[data-sell]').click();await page.waitForFunction(()=>player.credits===83);assert.equal(await page.evaluate(()=>player.inventory.find(e=>e.itemId==='armor').qty),1);assert.equal(await page.evaluate(()=>player.equipmentSlots.armor),'armor');
 await page.locator('[data-trade-search]').fill('SCR');assert.equal(await market('armor').count(),0);await page.locator('[data-trade-search]').fill('');await page.locator('[data-trade-category]').selectOption({label:'Броня (1)'});assert.equal(await market('gun').count(),0);await page.locator('[data-trade-category]').selectOption('all');
 await market('gun').click();await page.locator('[data-trade-quantity]').fill('10000');assert.equal(await buy.isDisabled(),true);await page.locator('[data-trade-quantity]').fill('1');assert.equal(await buy.isEnabled(),true);
 await page.evaluate(()=>{player.carryWeightMax=1;});await page.waitForFunction(()=>document.querySelector('[data-buy]').disabled);assert.ok((await page.locator('[data-trade-error]').textContent()).includes('вес'));await page.evaluate(()=>player.carryWeightMax=100);await page.waitForFunction(()=>!document.querySelector('[data-buy]').disabled);
 await market('token').dragTo(page.locator('[data-trade-inventory]'));await page.waitForFunction(()=>player.credits===78);assert.equal(await page.evaluate(()=>player.inventory.find(e=>e.itemId==='token').qty),1);
 assert.ok(await market('token').locator('[aria-label="Image unavailable"]').count());
 await market('gun').click();await page.evaluate(()=>campaign.marketDate='3616-10-08');await buy.click();await page.waitForFunction(()=>document.querySelector('.hub-trade-v163 [data-status]').textContent.includes('assortment changed'));assert.equal(await page.evaluate(()=>player.credits),78);
 await page.evaluate(()=>campaign.marketDate='3616-10-07');
 for(const width of [1440,760,390]){await page.setViewportSize({width,height:960});const r=await page.locator('.hub-trade-window-v163').boundingBox();assert.ok(r.x>=0&&r.width<=width);if(width===1440){await fs.mkdir('/tmp/grpgi-merchant-v163-shots',{recursive:true});await page.screenshot({path:'/tmp/grpgi-merchant-v163-shots/'+folder.replaceAll('/','-')+'.png'});}if(width===390)await page.screenshot({path:'/tmp/grpgi-merchant-v163-shots/'+folder.replaceAll('/','-')+'-mobile.png'});}
 await page.setViewportSize({width:1440,height:960});await market('gun').click();await page.evaluate(()=>delay=400);await buy.click();await page.locator('[data-close]').click();await page.waitForFunction(()=>player.credits===68);assert.equal(await page.locator('.hub-trade-v163').count(),0);
 assert.deepEqual(errors,[]);console.log(folder+': real inventory layout/bridge, images, size tiles, left purchase area, stats, categories, quantity, save retry, equipped protection, sales, capacity, drag/drop, stale quotes, responsive and Leave while saving passed');await page.close();
 }}finally{await browser.close();}
