"use strict";

var VERSION=149,MIN_PRICE=.01,MAX_CANDLES=720,TICK_SECONDS=10;
function num(value,fallback){var n=Number(value);return isFinite(n)?n:(fallback||0);}
function clamp(value,min,max){return Math.min(max,Math.max(min,num(value)));}
function round(value,digits){var scale=Math.pow(10,digits==null?4:digits);return Math.round(num(value)*scale)/scale;}
function hash32(value){var text=String(value==null?'':value),hash=0x811c9dc5;for(var i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,0x01000193);}return hash>>>0;}
function random(seed){return hash32(seed)/0x100000000;}
function nowMs(){return Date.now();}
function iso(ms){return new Date(ms==null?nowMs():ms).toISOString();}
function object(value){return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}
function list(value){return Array.isArray(value)?value:[];}
function jsonValue(value,fallback){if(value==null)return fallback;if(typeof value==='string'){try{return JSON.parse(value);}catch(error){return fallback;}}try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
function clone(value){return jsonValue(value,{});}
function recordJson(record,field){var raw=record.get(field);if(raw==null)return{};var decoded=JSON.parse(typeof raw==='string'?raw:toString(raw));if(!decoded||typeof decoded!=='object'||Array.isArray(decoded))throw new Error('Expected JSON object in '+field);return decoded;}
function stockItems(world){var found={};function visit(value){value=jsonValue(value,value);if(Array.isArray(value)){value.forEach(visit);return;}if(!value||typeof value!=='object')return;var type=String(value.type||value.category||'').toLowerCase(),id=String(value.id||'');if(id&&(['stock','stocks','share','shares'].indexOf(type)>=0||id.indexOf('stock_')===0))found[id]=value;Object.keys(value).forEach(function(key){visit(value[key]);});}visit(world);return Object.keys(found).map(function(id){return found[id];});}
function initialPrice(item){return Math.max(MIN_PRICE,num(item.stockMinPrice!=null?item.stockMinPrice:item.stockPriceMin!=null?item.stockPriceMin:item.marketMinPrice!=null?item.marketMinPrice:item.priceMin!=null?item.priceMin:item.minPrice!=null?item.minPrice:item.stockPrice!=null?item.stockPrice:item.basePrice,100));}
function volatility(item){return clamp(item.stockVolatility!=null?item.stockVolatility:item.volatility!=null?item.volatility:1,.05,8);}
function ticker(item){return String(item.ticker||item.symbol||item.id||'STOCK').toUpperCase().replace(/[^A-ZА-Я0-9._-]/g,'').slice(0,12);}
function createState(world,now){var tick=Math.floor(num(now,nowMs())/1000/TICK_SECONDS)*TICK_SECONDS,quotes={};stockItems(world).forEach(function(item){var price=initialPrice(item);quotes[item.id]={itemId:item.id,ticker:ticker(item),price:price,previousPrice:price,change:0,changePercent:0,volatility:volatility(item),tick:tick};});return{version:VERSION,lastTick:tick,quotes:quotes,candles:{},orders:[],events:[],updatedAt:iso(tick*1000)};}
function normalize(state,world,now){var next=object(state);if(!next.version)next=createState(world,now);next.quotes=object(next.quotes);next.candles=object(next.candles);next.orders=list(next.orders);next.events=list(next.events);stockItems(world).forEach(function(item){var configured=initialPrice(item);if(!next.quotes[item.id]){next.quotes[item.id]={itemId:item.id,ticker:ticker(item),price:configured,previousPrice:configured,change:0,changePercent:0,volatility:volatility(item),tick:next.lastTick||Math.floor(now/1000)};}else if(num(next.quotes[item.id].price)<=MIN_PRICE&&configured>MIN_PRICE){next.quotes[item.id].price=configured;next.quotes[item.id].previousPrice=configured;next.quotes[item.id].change=0;next.quotes[item.id].changePercent=0;next.quotes[item.id].anchor=configured;}next.quotes[item.id].volatility=volatility(item);});return next;}
function regime(campaign,itemId,tick){var block=Math.floor(tick/90),value=random(campaign+'|'+itemId+'|regime|'+block);if(value<.18)return{id:'trend-up',drift:.00042,reversion:.03,noise:1};if(value<.36)return{id:'trend-down',drift:-.00038,reversion:.03,noise:1};if(value<.56)return{id:'volatile',drift:0,reversion:.015,noise:2.1};if(value<.76)return{id:'range',drift:0,reversion:.12,noise:.65};if(value<.88)return{id:'breakout',drift:(random(campaign+'|'+itemId+'|breakout|'+block)<.5?-1:1)*.00085,reversion:.01,noise:1.35};return{id:'calm',drift:.00003,reversion:.06,noise:.3};}
function impulse(state,itemId,tick){return state.events.filter(function(event){return event.itemId===itemId&&tick>=event.startTick&&tick<event.startTick+event.duration;}).reduce(function(sum,event){return sum+num(event.percent)/100/Math.max(1,event.duration)*TICK_SECONDS;},0);}
function nextPrice(state,campaign,quote,tick){var mode=regime(campaign,quote.itemId,tick),vol=quote.volatility||1,noise=(random(campaign+'|'+quote.itemId+'|noise|'+tick)-.5)*.0014*vol*mode.noise,anchor=Math.max(MIN_PRICE,num(quote.anchor,quote.price)),deviation=(anchor-quote.price)/Math.max(anchor,MIN_PRICE),shockRoll=random(campaign+'|'+quote.itemId+'|shock|'+tick),shock=shockRoll>.998?(random(campaign+'|'+quote.itemId+'|shock-dir|'+tick)<.5?-1:1)*(.008+random(campaign+'|'+quote.itemId+'|shock-size|'+tick)*.025)*vol:0,delta=mode.drift*vol+noise+deviation*mode.reversion*.01+shock+impulse(state,quote.itemId,tick);return{price:Math.max(MIN_PRICE,round(quote.price*Math.exp(delta),4)),regime:mode.id};}
function candle(state,itemId,tick,price){var rows=state.candles[itemId]||(state.candles[itemId]=[]),minute=Math.floor(tick/60)*60,row=rows[rows.length-1];if(!row||row.time!==minute){row={time:minute,open:price,high:price,low:price,close:price,volume:0};rows.push(row);}row.high=Math.max(row.high,price);row.low=Math.min(row.low,price);row.close=price;row.volume=round(row.volume+random(itemId+'|volume|'+tick)*40+1,2);if(rows.length>MAX_CANDLES)rows.splice(0,rows.length-MAX_CANDLES);}
function indicators(rows){var closes=list(rows).map(function(row){return num(row.close);}),average=function(length){if(closes.length<length)return null;return round(closes.slice(-length).reduce(function(a,b){return a+b;},0)/length,4);},sample=closes.slice(-15),gains=0,losses=0;for(var i=1;i<sample.length;i++){var diff=sample[i]-sample[i-1];if(diff>=0)gains+=diff;else losses-=diff;}var rs=losses===0?100:gains/losses;return{sma5:average(5),sma20:average(20),rsi14:sample.length<15?null:round(100-100/(1+rs),2)};}
function triggers(order,quote){var price=quote.price,trigger=num(order.triggerPrice),limit=num(order.limitPrice);if(order.type==='market')return true;if(order.type==='limit')return['open_long','close_short'].indexOf(order.intent)>=0?price<=limit:price>=limit;if(order.type==='stop_loss')return order.intent==='close_long'?price<=trigger:price>=trigger;if(order.type==='take_profit')return order.intent==='close_long'?price>=trigger:price<=trigger;if(order.type==='trailing_stop'){order.peak=order.intent==='close_long'?Math.max(num(order.peak,price),price):Math.min(num(order.peak,price),price);return order.intent==='close_long'?price<=order.peak*(1-order.trailingPercent/100):price>=order.peak*(1+order.trailingPercent/100);}return false;}
function portfolio(player){player.stockPortfolio=object(player.stockPortfolio);player.stockPortfolio.positions=object(player.stockPortfolio.positions);player.stockPortfolio.shortPositions=object(player.stockPortfolio.shortPositions);player.stockPortfolio.ledger=list(player.stockPortfolio.ledger);return player.stockPortfolio;}
function execute(order,quote,player,tick){var book=portfolio(player),qty=Math.max(1,Math.trunc(num(order.quantity,1))),price=quote.price,total=round(price*qty,4),leverage=clamp(order.leverage||1,1,3),position,margin,average,share;if(order.intent==='open_long'){margin=total/leverage;if(num(player.credits)<margin)throw new BadRequestError('Недостаточно средств для открытия позиции');player.credits=round(num(player.credits)-margin,4);position=book.positions[order.itemId]||{itemId:order.itemId,knownQty:0,costBasis:0,margin:0,leverage:leverage};position.knownQty+=qty;position.costBasis+=total;position.margin=num(position.margin)+margin;position.leverage=leverage;book.positions[order.itemId]=position;}else if(order.intent==='close_long'){position=book.positions[order.itemId];if(!position||num(position.knownQty)<qty)throw new BadRequestError('Недостаточно акций в длинной позиции');average=num(position.costBasis)/position.knownQty;share=num(position.margin,position.costBasis)*qty/position.knownQty;player.credits=round(num(player.credits)+share+(price-average)*qty,4);position.knownQty-=qty;position.costBasis-=average*qty;position.margin=Math.max(0,num(position.margin)-share);if(position.knownQty<=0)delete book.positions[order.itemId];}else if(order.intent==='open_short'){margin=total/leverage;if(num(player.credits)<margin)throw new BadRequestError('Недостаточно средств для открытия шорта');player.credits=round(num(player.credits)-margin,4);position=book.shortPositions[order.itemId]||{itemId:order.itemId,quantity:0,costBasis:0,margin:0,leverage:leverage};position.quantity+=qty;position.costBasis+=total;position.margin+=margin;position.leverage=leverage;book.shortPositions[order.itemId]=position;}else if(order.intent==='close_short'){position=book.shortPositions[order.itemId];if(!position||position.quantity<qty)throw new BadRequestError('Недостаточно акций в короткой позиции');average=position.costBasis/position.quantity;share=position.margin*qty/position.quantity;player.credits=round(num(player.credits)+share+(average-price)*qty,4);position.quantity-=qty;position.costBasis-=average*qty;position.margin-=share;if(position.quantity<=0)delete book.shortPositions[order.itemId];}else throw new BadRequestError('Неизвестное направление заявки');var ledger={id:order.id,type:order.intent,itemId:order.itemId,quantity:qty,unitPrice:price,total:total,leverage:leverage,createdAt:iso(tick*1000)};book.ledger.push(ledger);if(book.ledger.length>500)book.ledger.splice(0,book.ledger.length-500);return ledger;}
function liquidate(player,quotes,tick){var book=portfolio(player),events=[];Object.keys(book.positions).forEach(function(itemId){var p=book.positions[itemId],q=quotes[itemId],qty=num(p.knownQty),entry=qty>0?num(p.costBasis)/qty:0,lev=clamp(p.leverage||1,1,3);if(!q||!qty||q.price>entry*(1-.9/lev))return;var payout=Math.max(0,num(p.margin,p.costBasis)+(q.price-entry)*qty);player.credits=round(num(player.credits)+payout,4);delete book.positions[itemId];events.push({id:'liq_'+tick+'_'+itemId,type:'liquidation_long',itemId:itemId,quantity:qty,unitPrice:q.price,leverage:lev,total:payout,createdAt:iso(tick*1000)});});Object.keys(book.shortPositions).forEach(function(itemId){var p=book.shortPositions[itemId],q=quotes[itemId],qty=num(p.quantity),entry=qty>0?num(p.costBasis)/qty:0,lev=clamp(p.leverage||1,1,3);if(!q||!qty||q.price<entry*(1+.9/lev))return;var payout=Math.max(0,num(p.margin)+(entry-q.price)*qty);player.credits=round(num(player.credits)+payout,4);delete book.shortPositions[itemId];events.push({id:'liq_'+tick+'_'+itemId,type:'liquidation_short',itemId:itemId,quantity:qty,unitPrice:q.price,leverage:lev,total:payout,createdAt:iso(tick*1000)});});book.ledger.push.apply(book.ledger,events);return events;}
function advance(state,campaign,world,now,onTick){var next=normalize(state,world,now),target=Math.floor(now/1000/TICK_SECONDS)*TICK_SECONDS,start=Math.max(Math.floor(num(next.lastTick,target)/TICK_SECONDS)*TICK_SECONDS,target-86400);for(var tick=start+TICK_SECONDS;tick<=target;tick+=TICK_SECONDS){Object.keys(next.quotes).forEach(function(id){var quote=next.quotes[id],previous=quote.price,movement=nextPrice(next,campaign,quote,tick);quote.previousPrice=previous;quote.price=movement.price;quote.change=round(quote.price-previous,4);quote.changePercent=previous>0?round(quote.change/previous*100,4):0;quote.regime=movement.regime;quote.tick=tick;candle(next,id,tick,quote.price);});next.lastTick=tick;if(onTick)onTick(next,tick);}next.events=next.events.filter(function(event){return target<event.startTick+event.duration;});next.updatedAt=iso(target*1000);return next;}
function findSnapshot(app,campaign){return app.findFirstRecordByFilter('campaign_snapshots','campaignId={:campaign}',{campaign:campaign});}
function findPlayer(app,campaign,playerId){return app.findFirstRecordByFilter('campaign_players','campaignId={:campaign} && playerId={:player}',{campaign:campaign,player:playerId});}
function savePlayer(app,row,player,actor){row.set('playerJson',player);row.set('version',num(row.get('version'))+1);row.set('updatedBy',actor);row.set('clientUpdatedAt',iso());app.save(row);}
function ensureTable(app){app.db().newQuery('CREATE TABLE IF NOT EXISTS grpgi_stock_exchange_state_v148 (campaign_id TEXT PRIMARY KEY NOT NULL, state_json TEXT NOT NULL, updated_at TEXT NOT NULL)').execute();}
function loadState(app,campaign){var row=new DynamicModel({stateJson:''});app.db().newQuery("SELECT COALESCE((SELECT state_json FROM grpgi_stock_exchange_state_v148 WHERE campaign_id={:campaign}), '{}') AS stateJson").bind({campaign:campaign}).one(row);var state=JSON.parse(row.stateJson);if(!state||typeof state!=='object'||Array.isArray(state))throw new Error('Invalid stored stock state');return state;}
function saveState(app,campaign,state){app.db().newQuery('INSERT INTO grpgi_stock_exchange_state_v148 (campaign_id,state_json,updated_at) VALUES ({:campaign},{:state},{:updated}) ON CONFLICT(campaign_id) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at').bind({campaign:campaign,state:JSON.stringify(state),updated:iso()}).execute();}
function mutateCampaign(app,campaign,callback){var output;ensureTable(app);app.runInTransaction(function(tx){var snapshot=findSnapshot(tx,campaign),world=recordJson(snapshot,'worldJson'),state=loadState(tx,campaign),players={};tx.findRecordsByFilter('campaign_players','campaignId={:campaign}','',0,0,{campaign:campaign}).forEach(function(row){players[String(row.get('playerId'))]=row;});function player(id){if(!players[id])players[id]=findPlayer(tx,campaign,id);return players[id];}state=advance(state,campaign,world,nowMs(),function(current,tick){Object.keys(players).forEach(function(id){var row=players[id],data=recordJson(row,'playerJson');if(liquidate(data,current.quotes,tick).length)savePlayer(tx,row,data,'stock-liquidation-v148');});current.orders.filter(function(order){return order.status==='pending';}).forEach(function(order){var quote=current.quotes[order.itemId];if(!quote||!triggers(order,quote))return;try{var row=player(order.playerId),data=recordJson(row,'playerJson');order.execution=execute(order,quote,data,tick);order.status='filled';order.filledAt=iso(tick*1000);order.fillPrice=quote.price;savePlayer(tx,row,data,'stock-exchange-v148');}catch(error){order.status='rejected';order.rejectedAt=iso(tick*1000);order.message=String(error.message||error);}});});output=callback?callback(tx,snapshot,world,state,player):null;saveState(tx,campaign,state);});return output;}
function publicState(state,playerId){return{ok:true,version:VERSION,serverTime:iso(),lastTick:state.lastTick,updatedAt:state.updatedAt,quotes:Object.keys(state.quotes).map(function(id){var q=clone(state.quotes[id]);q.indicators=indicators(state.candles[id]);return q;}),candles:state.candles,orders:state.orders.filter(function(order){return order.playerId===playerId;}).slice(-100)};}
function body(e){var model=new DynamicModel({campaignId:'',playerId:'',itemId:'',operationId:'',orderId:'',type:'',intent:'',quantity:0,leverage:1,triggerPrice:0,limitPrice:0,trailingPercent:1,percent:0,duration:60,targetPrice:0});e.bindBody(model);return model;}
function createOrder(data){var types=['market','limit','stop_loss','take_profit','trailing_stop'],intents=['open_long','close_long','open_short','close_short'];if(!data.operationId)throw new BadRequestError('operationId обязателен');return{id:String(data.operationId),playerId:String(data.playerId),itemId:String(data.itemId),type:types.indexOf(data.type)>=0?data.type:'market',intent:intents.indexOf(data.intent)>=0?data.intent:'open_long',quantity:Math.max(1,Math.min(10000,Math.trunc(num(data.quantity,1)))),leverage:clamp(data.leverage||1,1,3),triggerPrice:Math.max(0,num(data.triggerPrice)),limitPrice:Math.max(0,num(data.limitPrice)),trailingPercent:clamp(data.trailingPercent||1,.1,50),status:'pending',createdAt:iso()};}
function get(e){var campaign=String(e.request.url.query().get('campaignId')||''),playerId=String(e.request.url.query().get('playerId')||'');if(!campaign||!playerId)throw new BadRequestError('campaignId и playerId обязательны');ensureTable(e.app);var snapshot=findSnapshot(e.app,campaign),world=recordJson(snapshot,'worldJson'),state=normalize(loadState(e.app,campaign),world,nowMs()),row=findPlayer(e.app,campaign,playerId),payload=publicState(state,playerId);payload.player=recordJson(row,'playerJson');return e.json(200,payload);}
function order(e){var data=body(e),payload;if(!data.campaignId||!data.playerId)throw new BadRequestError('campaignId и playerId обязательны');mutateCampaign(e.app,String(data.campaignId),function(tx,snapshot,world,state,player){player(String(data.playerId));var existing=state.orders.filter(function(row){return row.id===String(data.operationId);})[0];var next=existing||createOrder(data);if(existing&&(existing.playerId!==String(data.playerId)||existing.itemId!==String(data.itemId)))throw new BadRequestError('operationId уже использован');if(!state.quotes[next.itemId])throw new BadRequestError('Акция не найдена');if(!existing)state.orders.push(next);if(next.status==='pending'&&next.type==='market'){try{var row=player(next.playerId),profile=recordJson(row,'playerJson');next.execution=execute(next,state.quotes[next.itemId],profile,state.lastTick);next.status='filled';next.filledAt=iso();next.fillPrice=state.quotes[next.itemId].price;savePlayer(tx,row,profile,'stock-exchange-v148');}catch(error){next.status='rejected';next.message=String(error.message||error);}}payload=publicState(state,next.playerId);payload.status=next.status;payload.order=next;payload.ok=next.status!=='rejected';payload.player=recordJson(player(next.playerId),'playerJson');});return e.json(payload.ok?200:400,payload);}
function cancel(e){var data=body(e),payload;mutateCampaign(e.app,String(data.campaignId),function(tx,snapshot,world,state,player){player(String(data.playerId));var found=state.orders.filter(function(row){return row.id===String(data.orderId)&&row.playerId===String(data.playerId)&&row.status==='pending';})[0];if(!found)throw new NotFoundError('Активная заявка не найдена');found.status='cancelled';found.cancelledAt=iso();payload={ok:true,status:'cancelled',order:found};});return e.json(200,payload);}
function manualImpulse(e){var data=body(e),payload;mutateCampaign(e.app,String(data.campaignId),function(tx,snapshot,world,state,player){var profile=recordJson(player(String(data.playerId)),'playerJson'),role=String(profile.role||'').toLowerCase(),id=String(data.itemId),q=state.quotes[id];if(['gm','dm','master'].indexOf(role)<0)throw new ForbiddenError('Ручная корректировка доступна ведущему');if(!q)throw new NotFoundError('Акция не найдена');if(num(data.targetPrice,0)>0){var previous=q.price;q.previousPrice=previous;q.price=round(Math.max(MIN_PRICE,num(data.targetPrice,previous)),4);q.change=round(q.price-previous,4);q.changePercent=previous>0?round(q.change/previous*100,4):0;q.anchor=q.price;candle(state,id,state.lastTick,q.price);payload={ok:true,status:'price-set',price:q.price};return;}state.events.push({id:'evt_'+state.lastTick+'_'+id,itemId:id,percent:clamp(data.percent,-50,50),duration:clamp(Math.trunc(num(data.duration,60)),TICK_SECONDS,3600),startTick:state.lastTick+TICK_SECONDS,createdAt:iso()});payload={ok:true,status:'scheduled'};});return e.json(200,payload);}
function tickAll(e){var expected=String($os.getenv('GRPGI_STOCK_WORKER_TOKEN')||''),actual=String(e.request.header.get('X-GRPGI-Worker-Token')||'');if(!expected||actual!==expected)throw new UnauthorizedError('Invalid worker token');var snapshots=e.app.findRecordsByFilter('campaign_snapshots','','',0,0),done=[];snapshots.forEach(function(row){var campaign=String(row.get('campaignId')||'');if(!campaign)return;mutateCampaign(e.app,campaign,null);done.push(campaign);});return e.json(200,{ok:true,serverTime:iso(),campaigns:done});}
module.exports={get:get,order:order,cancel:cancel,manualImpulse:manualImpulse,tickAll:tickAll,advance:advance,createState:createState,indicators:indicators};
